# Generated by Django 3.1.4 on 2021-12-20 07:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100000)),
                ('name_english', models.CharField(max_length=100000)),
                ('url', models.URLField()),
                ('business_information', models.CharField(max_length=100000)),
                ('error', models.CharField(max_length=100000)),
                ('pdf_etc', models.CharField(max_length=100000)),
                ('company_num', models.CharField(max_length=100000)),
                ('prefacture', models.CharField(max_length=100000)),
                ('city', models.CharField(max_length=100000)),
                ('address_etc', models.CharField(max_length=100000)),
                ('location', models.CharField(max_length=100000)),
                ('head_office_address', models.CharField(max_length=100000)),
                ('year_of_establishment', models.CharField(max_length=100000)),
                ('month_of_establishment', models.CharField(max_length=100000)),
                ('date_of_establishment', models.CharField(max_length=100000)),
                ('capital', models.CharField(max_length=100000)),
                ('full_time_employees', models.CharField(max_length=100000)),
                ('net_sales', models.CharField(max_length=100000)),
                ('operating_income', models.CharField(max_length=100000)),
                ('offering_period', models.CharField(max_length=100000)),
                ('listed_market_name', models.CharField(max_length=100000)),
                ('technology_code', models.CharField(max_length=100000)),
                ('technology_field', models.CharField(max_length=100000)),
                ('service_supply_code', models.CharField(max_length=100000)),
                ('service_supply', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suggest_1', models.ForeignKey(db_column='suggest_1', on_delete=django.db.models.deletion.CASCADE, related_name='suggest_1', to='main_api.company')),
                ('suggest_2', models.ForeignKey(db_column='suggest_2', on_delete=django.db.models.deletion.CASCADE, related_name='suggest_2', to='main_api.company')),
                ('suggest_3', models.ForeignKey(db_column='suggest_3', on_delete=django.db.models.deletion.CASCADE, related_name='suggest_3', to='main_api.company')),
                ('target', models.ForeignKey(db_column='target', on_delete=django.db.models.deletion.CASCADE, related_name='target', to='main_api.company')),
            ],
        ),
    ]
