# Generated by Django 3.1.4 on 2021-12-10 07:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100000)),
                ('name_english', models.CharField(max_length=100000)),
                ('url', models.URLField()),
                ('business_information', models.CharField(max_length=100000)),
                ('error', models.CharField(max_length=100000)),
                ('pdf_etc', models.CharField(max_length=100000)),
                ('company_num', models.CharField(max_length=100000)),
                ('prefacture', models.CharField(max_length=100000)),
                ('city', models.CharField(max_length=100000)),
                ('address_etc', models.CharField(max_length=100000)),
                ('location', models.CharField(max_length=100000)),
                ('head_office_address', models.CharField(max_length=100000)),
                ('year_of_establishment', models.CharField(max_length=100000)),
                ('month_of_establishment', models.CharField(max_length=100000)),
                ('date_of_establishment', models.CharField(max_length=100000)),
                ('capital', models.CharField(max_length=100000)),
                ('full_time_employees', models.CharField(max_length=100000)),
                ('net_sales', models.CharField(max_length=100000)),
                ('operating_income', models.CharField(max_length=100000)),
                ('offering_period', models.CharField(max_length=100000)),
                ('listed_market_name', models.CharField(max_length=100000)),
                ('technology_code', models.CharField(max_length=100000)),
                ('technology_field', models.CharField(max_length=100000)),
                ('service_supply_code', models.CharField(max_length=100000)),
                ('service_supply', models.CharField(max_length=100000)),
            ],
        ),
    ]
