# Generated by Django 3.1.4 on 2021-12-08 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='town',
        ),
    ]
