# Generated by Django 3.1.4 on 2021-12-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0002_remove_company_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='capital',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_num',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='company',
            name='full_time_employees',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='company',
            name='net_sales',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='company',
            name='offering_period',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='company',
            name='operating_income',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='company',
            name='service_supply_code',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='company',
            name='technology_code',
            field=models.CharField(max_length=64),
        ),
    ]
