# Generated by Django 3.1.4 on 2021-12-20 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0004_auto_20211210_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='suggest_1',
            field=models.ForeignKey(db_column='suggest_1', on_delete=django.db.models.deletion.CASCADE, related_name='sugest_1', to='main_api.company'),
        ),
        migrations.AlterField(
            model_name='result',
            name='suggest_2',
            field=models.ForeignKey(db_column='suggest_2', on_delete=django.db.models.deletion.CASCADE, related_name='sugest_2', to='main_api.company'),
        ),
        migrations.AlterField(
            model_name='result',
            name='suggest_3',
            field=models.ForeignKey(db_column='suggest_3', on_delete=django.db.models.deletion.CASCADE, related_name='sugest_3', to='main_api.company'),
        ),
        migrations.AlterField(
            model_name='result',
            name='target',
            field=models.ForeignKey(db_column='target', on_delete=django.db.models.deletion.CASCADE, related_name='target', to='main_api.company'),
        ),
    ]
