# Generated by Django 3.1.4 on 2021-12-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0005_auto_20211210_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='business_information',
            field=models.CharField(max_length=8192),
        ),
    ]
